{% set name = "enpt_enmapboxapp" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt_enmapboxapp-{{ version }}.tar.gz
  sha256: 0e3d3a988abcf76b42a0c430b5ac857bbe39d6ce22369ceb1fe4e5cdd79cedc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - packaging
  run:
    - python >=3.8
    - packaging
    - psutil

test:
  imports:
    - enpt_enmapboxapp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enpt_enmapboxapp
  summary: A QGIS EnMAPBox plugin providing a GUI for the EnMAP processing tool (EnPT).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
