{% set name = "enpt_enmapboxapp" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enpt_enmapboxapp-{{ version }}.tar.gz
  sha256: 30b8f8442bf2ee9073f343b917e0ee6da66bf1ba33b3e8383c986055fc1d999c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - packaging
  run:
    - python >={{ python_min }}
    - packaging
    - psutil

test:
  imports:
    - enpt_enmapboxapp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enpt_enmapboxapp
  summary: A QGIS EnMAPBox plugin providing a GUI for the EnMAP processing tool (EnPT).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
