{% set name = "enpt_enmapboxapp" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt_enmapboxapp-{{ version }}.tar.gz
  sha256: f83e036ff5f7050c6026d709efb14f4159db90fd2a96623e150b744b0ad869e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - importlib-metadata
    - packaging
  run:
    - python >=3.8
    - importlib-metadata
    - packaging
    - psutil

test:
  imports:
    - enpt_enmapboxapp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enpt_enmapboxapp
  summary: A QGIS EnMAPBox plugin providing a GUI for the EnMAP processing tool (EnPT).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
